version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-client:
    executor:
      name: node/default
    - working_directory: ~/client
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  build-server:
    executor:
      name: node/default
    - working_directory: ~/server
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
workflows:
    build-server-client:
      jobs:
        - build-server
        - build-client