version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd ./client && npm install
            - run: cd ./client && npm run build
  build-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd ./server && npm install
            - run: cd ./server && npm run build
workflows:
    build-server-client:
      jobs:
        - build-server
        - build-client